sudo: false

language: java
jdk: oraclejdk8

after_success:
- sh push_release.sh

deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: MWQqc/sJuaWMGAYoWiHT3OxmUBIcSEtZgJk1NKXJWI9TzZiPgrIBRNW7xmaftd3/oLi/WdYasxnFK814mYBa9G/UCLqMGo8WHYvYAYsiLeZvMtC0vUAwgyAvinJnlEKi+69FHrFr8VvzBZs7gkxIiega7j5p0co1/LC9s0/nERI90txSdi2DBmLWZK7PXnIm8kvoo+VDgpzXl9bjEWoxipUKRd/HYPtyWHmdKRINdqdaI5wBK2m8/81Dff3wJO2v7VB3z/VJ7NmC0qCkpdxbNtmXCwAzsMqxxaR34PFCkq89TnXu16PGolWlaALTfc9jL9UEcXIgpTiCbywGXrEW4GGGPWmU2I9Dq+wsDVXhLOQnBPd2PFTkFe0IP8l2TpSCb40XFvrMQ3aL0EYzSeFbt24op0sRb3I8w/Ap5O0NWfGjIRKfU1Gx5ZWYS/b8yK2ToeBhjeW5btBnAWwLha96IbE6qghw4riq3MThWePEL9PG/+ki3ElYcKCW7HjbE0p0Q54Sl+bZ+xbhrzjftTusg/XdufgRJh4IIX1JyuhMYofU6Vrmdjrfdt47G8D5i++HQiXlYxqrVGYsZI+h0YDTUbrbnmyH/RFQFnXkrRCF1kSoqrOgAvzi8QkrVbiQkDu1BO07VYdcIeNm/s3xg65fELzrKTXt8hOVQkjFAkTemjo=
  file: target/myZone.jar
  on:
    repo: TryHardDood/myZone
    branch: heads/v1.1
script: mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true clean package
  
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - node ./node_modules/grunt-cli/bin/grunt release

