language: java
install: true

matrix:
  include:
  - jdk: oraclejdk8
  
script:
- mvn clean package

after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG="myZone $TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER"
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push origin $GIT_TAG

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lamyyqyZ8i17UsyccFUvyLwUFMoRo4cg62HdNpN7X0sC2RrcnmqW1wNE3XqZfbIUQdGwfVIThESRc31PwPO5gCQRkhJG4+1AxZAtu/asn6CPZVjE+Y5Z00nsa/m0lEdFw1iRBvoNAJbXFsgtKNcPxmBBPEGM5i6mljTeYOgSNy87RNJsEe5jEhdPHTSMNyCQa6cPuTXU/FBHV43P6SNZVqrBIknLUSgB0RiPiefsG21sEw0DW1sIqSwju7Fe2BY3yjNUi804ol7FmMZDTvLj/PpnjkJZEQ30bsYUuJ4xhUdX04Mzd9XQUxEjgwPyKf13iYE3PIYSRN9mT6WEK/YXT3+ApeIEWgMIJigDsbiu3//93gY7GLiTPpJ4EFO45qcP9/fW8WkA2yF0b5TRc3z9Bvry4nOFPKd9bFmKDXg3bPIt9hQa3BBi8x4dYe7b+Be2mb1b0NpuhEUOn0hzQHFNv6+U+aSzbVrWkw8/4VzQwYAifELFBXvjHreliV0ZX4VnIefhslo21zN57oepcQbNWFDB4PJTixWyIk2M22H+CXp3nv3/sqPK/Nf2mAOcbmzhwF7MhNhcKQGdK7dHstWfOuxCIJLPGTDRDktnGGKEUIi8dqD1fOH1zu10fgCFeMawdS2Vj1oCuwVKpMIss0p2hY9rohT38DHJr1jWQikvHvY=
  file: target/myZone.jar
  on:
    repo: TryHardDood/myZone
    branch: v1.1

env:
  global:
    secure: lmwJQW9kGHRc7b/RnblY1LJ3Oq5nN/zu5QVoCRjKAL5l1tEOmmQDXmn8i30ZScyD42poWT3Ts2Z4Yacl8xhYh1ZhAE5NEuDMImyvGIwn+TX63n54nwxcs84X2HN7sbmQEEZ5ZpJ5G7cGozLNjTpUB7X+/8k3LMG1kQzk2ljnGzAkpMdZhjTZmANjylMzzzmS839SBxGIYzmwOJ1S5oaQNENUw+hTF6+/RAIZBuIuveFLLr1o+hvi8N7UCqiJ+gMqxBL7Vg9NZA82rKmTuD0ZEbmvn5GllFFLKez22hkgIfT4tMxXp+LuZxtk81svOzvR+P/X4bbF5hPpd8PMauejXN5gi0ZhRP9CBqlWUkL0h2XZ3PJ9ZG6pOmyhzr19MP+UH9hTsESumYvBXJbB5QOVfLmenOalOBFe8d9UdT0rRzU5MdMlkZEwNomH0ehPcnD1uuedG2iFkM5Xxte5BImOx0WuAQ+yNmTwAlpFNAR7hLnyl1/gaz7tH4pKIrZ3K9qviIhqab2/ieABJ4AtujOjTvkViIdUMxol/2R6SeTfY0n6Cs/JblYKOSLIcF0aQBTwtT6WRn+z7IBJbNRz74TCNWDI55oFB91Q50b80iuX0dg7coiTVp5OGcCiA1LQ1T7T/yKvxxJ25DQrZGEtrHJQNoe6aSQeFUQoE2c435hiQ3c=
