sudo: false

language: java
jdk: oraclejdk8

after_success:
- sh push_release.sh

deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: ikonGGds/XXnkpQjt742dlare8Sqyd4rTu1ktVpYptlC8ztUN1T3Lu6TmCtI83Fw8Py2n7WZFyRsXXcg2PU8ISwxW50gJ3tv2gO+amYktkGiCYznp2Y2zbaOrWf8eKN3yF5GS02tJda0BGgzSTt6m46LWn8swcMfndjBvp093rxekLqGNVDByna5BK/0PsxI1pmfvjg4pqa2rOnRNV0zqzqdgIU+PFgbMYnLr1aO4S+Ds2KAb2SXoLFinJyPg1u0RXAmvId+5ZsBhFTSvaVm2PyVzJnZFRT2BSKVA61iW4YfvoFzvzR1VTKsaZlyAtFX6POnGjYl+bQcl7Ia+BQw/eHmwozzacxB+6tk9Yse18KPtqSVYbHBijlcIcZdhHGxmzGA9u/1F/VmDGOqSl/ypR2Goeer0DPPZB38PU7EinuI5i0hnfwKE+xgYvwnFn2Pu5sgal2T10UJiPE61MqxBdnn4vLVEnHjPHzEO0aNZ4WV/DuUeJailiOtiJJBIK1qq0bNKRU1mKnZXyClwpPrL9/QOIYwmaimEAYDDimLOm95ggTMxiMzwhuYSxlg0ZfTzlE+lLKuqfOxRh72T82x9hHFmwa41ph91K9cfx6kopNmMmr2cR9GJQnXR+49eKZ43QfIdGZgkMxhvnimKWiXfU1oVkLUE1faSx+EhYKWcSE=
  file: target/myZone.jar
  on:
    repo: TryHardDood/myZone
    branch: heads/v1.1

script: mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true clean package