language: java

install: true

matrix:
  include:
  - jdk: oraclejdk8

script:
  - mvn clean package

after_success:
- sh push_release.sh

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lamyyqyZ8i17UsyccFUvyLwUFMoRo4cg62HdNpN7X0sC2RrcnmqW1wNE3XqZfbIUQdGwfVIThESRc31PwPO5gCQRkhJG4+1AxZAtu/asn6CPZVjE+Y5Z00nsa/m0lEdFw1iRBvoNAJbXFsgtKNcPxmBBPEGM5i6mljTeYOgSNy87RNJsEe5jEhdPHTSMNyCQa6cPuTXU/FBHV43P6SNZVqrBIknLUSgB0RiPiefsG21sEw0DW1sIqSwju7Fe2BY3yjNUi804ol7FmMZDTvLj/PpnjkJZEQ30bsYUuJ4xhUdX04Mzd9XQUxEjgwPyKf13iYE3PIYSRN9mT6WEK/YXT3+ApeIEWgMIJigDsbiu3//93gY7GLiTPpJ4EFO45qcP9/fW8WkA2yF0b5TRc3z9Bvry4nOFPKd9bFmKDXg3bPIt9hQa3BBi8x4dYe7b+Be2mb1b0NpuhEUOn0hzQHFNv6+U+aSzbVrWkw8/4VzQwYAifELFBXvjHreliV0ZX4VnIefhslo21zN57oepcQbNWFDB4PJTixWyIk2M22H+CXp3nv3/sqPK/Nf2mAOcbmzhwF7MhNhcKQGdK7dHstWfOuxCIJLPGTDRDktnGGKEUIi8dqD1fOH1zu10fgCFeMawdS2Vj1oCuwVKpMIss0p2hY9rohT38DHJr1jWQikvHvY=
  file: target/myZone.jar
  on:
    repo: TryHardDood/myZone
    branch: heads/v1.1